schema = 3

[mod]
[mod.'charm.land/lipgloss/v2']
version = 'v2.0.0'
hash = 'sha256-O78AzqA19r2N7DpRwj7pCk57Spqo8FkdD1J8frGQqoc='

[mod.'code.gitea.io/sdk/gitea']
version = 'v0.23.2'
hash = 'sha256-qCkmecTnHYMkV3HUWJvPYgxeF/lHV+KeZG/D7fFX8AE='

[mod.'github.com/42wim/httpsig']
version = 'v1.2.3'
hash = 'sha256-Yrf21S5q6mupTtyk8izVKQciJC/aRDe7YRKL0cBkRpQ='

[mod.'github.com/BurntSushi/toml']
version = 'v1.6.0'
hash = 'sha256-ptdUJvuc21ixeLt+M5way/na3aCnCO4MYHWulWp8NEY='

[mod.'github.com/adrg/xdg']
version = 'v0.5.3'
hash = 'sha256-bo6tBgHS+3sl6f4oWpmdFrZjfV6eA/3xAlysSW0bIEs='

[mod.'github.com/aymanbagabas/go-osc52/v2']
version = 'v2.0.1'
hash = 'sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg='

[mod.'github.com/charmbracelet/colorprofile']
version = 'v0.4.2'
hash = 'sha256-AMnmwWjpv/TMb2mbqVXB4RmMVWBsrTFlq1FL8A00olw='

[mod.'github.com/charmbracelet/lipgloss']
version = 'v1.1.0'
hash = 'sha256-RHsRT2EZ1nDOElxAK+6/DC9XAaGVjDTgPvRh3pyCfY4='

[mod.'github.com/charmbracelet/log']
version = 'v0.4.2'
hash = 'sha256-3w1PCM/c4JvVEh2d0sMfv4C77Xs1bPa1Ea84zdynC7I='

[mod.'github.com/charmbracelet/ultraviolet']
version = 'v0.0.0-20260303162955-0b88c25f3fff'
hash = 'sha256-jszDf3Y15JhcH+zWFONJTrZGouEtHEVtYNg7MKcLSFg='

[mod.'github.com/charmbracelet/x/ansi']
version = 'v0.11.6'
hash = 'sha256-UToZIkqXl9MEppcRgbeBqaaMeAzRkGa0w3lVUs6sxWI='

[mod.'github.com/charmbracelet/x/cellbuf']
version = 'v0.0.15'
hash = 'sha256-0S60XaWhKZG+TB3Kqe1oMn2Okwdq53nym8XayVSHHiM='

[mod.'github.com/charmbracelet/x/term']
version = 'v0.2.2'
hash = 'sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4='

[mod.'github.com/charmbracelet/x/termios']
version = 'v0.1.1'
hash = 'sha256-sri3LpHCBhGvnJldDzBxwbbZpeSGZVCJFOUL45uBFds='

[mod.'github.com/charmbracelet/x/windows']
version = 'v0.2.2'
hash = 'sha256-CvmE8kAC5wlPSeWjl2hc5xizvGS2FeOLHw84froldkk='

[mod.'github.com/clipperhouse/displaywidth']
version = 'v0.11.0'
hash = 'sha256-WokyTaofEy95xlshqK5YDzpemhXV5oaQifxS9YyfCXo='

[mod.'github.com/clipperhouse/uax29/v2']
version = 'v2.7.0'
hash = 'sha256-GO3az7WiGcwU0OvmocwdfR5ohGRL8NbjscIaMyhAdxE='

[mod.'github.com/coder/websocket']
version = 'v1.8.14'
hash = 'sha256-3lTpVWweJJ+VjIIwcK9Ca+mWrbAYPxi4tx7anP1sFYw='

[mod.'github.com/davidmz/go-pageant']
version = 'v1.0.2'
hash = 'sha256-gfwm6i0ZGQhX2c0lDRe7qVXyHkhoHeemYpaj+O0aYyw='

[mod.'github.com/fsnotify/fsnotify']
version = 'v1.9.0'
hash = 'sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g='

[mod.'github.com/go-fed/httpsig']
version = 'v1.1.0'
hash = 'sha256-ok0PEEvSR010nh6vB3nDCyKSSVvoB50/UjVvBKOYXsA='

[mod.'github.com/go-logfmt/logfmt']
version = 'v0.6.1'
hash = 'sha256-+gUGmdR/QOsB9qKESLrsbq6tK2VssNT/kDbRFpgrZL4='

[mod.'github.com/go-viper/mapstructure/v2']
version = 'v2.5.0'
hash = 'sha256-LbrCBANBprVI84M0CWrXc7rriJL5ac5VKbh58LBTw7U='

[mod.'github.com/google/go-github/v84']
version = 'v84.0.0'
hash = 'sha256-PCi2rQfQ4L2pmgGwOFSIW1u+exocIaq94K0OzuA++5I='

[mod.'github.com/google/go-querystring']
version = 'v1.2.0'
hash = 'sha256-F/Ve4oDaEqho8RryvdGSRR22/DbYHWZQa6M60n6oSYM='

[mod.'github.com/google/uuid']
version = 'v1.6.0'
hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

[mod.'github.com/hashicorp/go-cleanhttp']
version = 'v0.5.2'
hash = 'sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ='

[mod.'github.com/hashicorp/go-retryablehttp']
version = 'v0.7.8'
hash = 'sha256-4LZwKaFBbpKi9lSq5y6lOlYHU6WMnQdGNMxTd33rN80='

[mod.'github.com/hashicorp/go-version']
version = 'v1.8.0'
hash = 'sha256-KXtqERmYrWdpqPCViWcHbe6jnuH7k16bvBIcuJuevj8='

[mod.'github.com/hasura/go-graphql-client']
version = 'v0.15.1'
hash = 'sha256-Cy8pWsgdlUy1LwOjXzZItYVNKRjJAdCgJTClrQOk7OU='

[mod.'github.com/inconshreveable/mousetrap']
version = 'v1.1.0'
hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

[mod.'github.com/lucasb-eyer/go-colorful']
version = 'v1.3.0'
hash = 'sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU='

[mod.'github.com/mattn/go-isatty']
version = 'v0.0.20'
hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

[mod.'github.com/mattn/go-runewidth']
version = 'v0.0.20'
hash = 'sha256-Y3qYfCqPt+Ce/MEk8dr6pSdd1ZwO2Nwm5sjLIbw26TY='

[mod.'github.com/muesli/cancelreader']
version = 'v0.2.2'
hash = 'sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ='

[mod.'github.com/muesli/termenv']
version = 'v0.16.0'
hash = 'sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI='

[mod.'github.com/pelletier/go-toml/v2']
version = 'v2.2.4'
hash = 'sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q='

[mod.'github.com/rivo/uniseg']
version = 'v0.4.7'
hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

[mod.'github.com/sagikazarmark/locafero']
version = 'v0.12.0'
hash = 'sha256-EXk9S5Z5sYyApAzCgHIugsGMbt/pHWRfHYFZH5D+5Ws='

[mod.'github.com/spf13/afero']
version = 'v1.15.0'
hash = 'sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8='

[mod.'github.com/spf13/cast']
version = 'v1.10.0'
hash = 'sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk='

[mod.'github.com/spf13/cobra']
version = 'v1.10.2'
hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

[mod.'github.com/spf13/pflag']
version = 'v1.0.10'
hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

[mod.'github.com/spf13/viper']
version = 'v1.21.0'
hash = 'sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI='

[mod.'github.com/subosito/gotenv']
version = 'v1.6.0'
hash = 'sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A='

[mod.'github.com/xo/terminfo']
version = 'v0.0.0-20220910002029-abceb7e1c41e'
hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='

[mod.'gitlab.com/gitlab-org/api/client-go']
version = 'v1.46.0'
hash = 'sha256-qciW11qwA5OUfQ5X+kDV7bKr0qfNf4+xEZYCfbzpmQc='

[mod.'go.yaml.in/yaml/v3']
version = 'v3.0.4'
hash = 'sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4='

[mod.'golang.org/x/crypto']
version = 'v0.48.0'
hash = 'sha256-uBIGGSGmWWklRxX6XTOqUECzz165UFY9Y99Ka3pLKAw='

[mod.'golang.org/x/exp']
version = 'v0.0.0-20260218203240-3dfff04db8fa'
hash = 'sha256-vsit1x+iQymfiWhINdZgd4wQhMoWMp3tqcjbDjcV0oY='

[mod.'golang.org/x/oauth2']
version = 'v0.35.0'
hash = 'sha256-QeleoXu+9K3LJZiw6/iPR+EQzi/OLDBTFdrP2/d1XN8='

[mod.'golang.org/x/sync']
version = 'v0.19.0'
hash = 'sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno='

[mod.'golang.org/x/sys']
version = 'v0.41.0'
hash = 'sha256-owjs3/IzAKfFlIz1U1fiHSfl2+bTUhaXTyWEjL5SWHk='

[mod.'golang.org/x/term']
version = 'v0.40.0'
hash = 'sha256-tu8USqDmcWfwery/+xti/BdUpNLbMNmZeghBNDsj1fQ='

[mod.'golang.org/x/text']
version = 'v0.34.0'
hash = 'sha256-wGKd1JkeiFROibvo2kkAuQ7JajSIfV4utGaoGbTQhQM='

[mod.'golang.org/x/time']
version = 'v0.14.0'
hash = 'sha256-fVjpq0ieUHVEOTSElDVleMWvfdcqojZchqdUXiC7NnY='

[mod.'gopkg.in/check.v1']
version = 'v1.0.0-20190902080502-41f04d3bba15'
hash = 'sha256-Xl5gjoqU26M+Yxm6Xok5VHVpYT5hItwsN7d2Wj9L020='
